config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :urls, only: [:index, :new, :show, :create], path: '/' do
    member do
      get :info
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
require 'uri'

class Url < ApplicationRecord
  has_many :visits

  # Validations
  validates :long_url, presence: true, uniqueness: true

  validate :validate_url

  # Validate to ensure the URL includes http:// or https://
  def is_valid_url?
    uri = URI.parse(self.long_url)
    return uri.is_a?(URI::HTTP) && !uri.host.nil?
  rescue URI::InvalidURIError
    return false
  end

  def validate_url
    errors.add(:long_url, 'is invalid.') unless is_valid_url?
  end

  # Convert base 10 to base 36 "short URL" - This creates a shorter URL, which is generated faster, and won't result in uniqueness conflicts
  def to_param
    # Return a string, as base 36 will be alphanumeric
    id.to_s(36)
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @urls = Url.all
    @url = Url.new
  end

  def show
    @url = Url.find(id_param)
    # Create a visit on click, adding the request's IP address
    @url.visits.create!(ip_address: request.remote_ip)
    redirect_to @url.long_url
  end

  def info
    @url = Url.find(id_param)
  end

  def new
    @url = Url.new
  end

  def create
    # Using find_or_create_by here upserts the record - creates or updates it, depending on whether or not it already exists. Create_with tells Rails what to use to create a new record if one does not exist.
    @url = Url.create_with(url_params).find_or_create_by(long_url: url_params[:long_url])

    if @url.save
      redirect_to [:info, @url]
    else
      flash[:error] = @url.errors.full_messages
      render :new
    end
  end

  private

  def id_param
    # Convert the base 36 string back to a base 10 integer so that ActiveRecord can find the record by its ID
    params[:id]&.to_i(36)
  end

  def url_params
    params.require(:url).permit(:long_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tinyurl
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/urls/_form.html.haml
- if @url.errors.any?
  - @url.errors.full_messages.each do |message|
    %h3= message
= form_with model: @url do |f|
  = f.text_field :long_url
  = f.submit "Shorten URL"

app/views/urls/index.html.haml
%h1 Shorten URL

= render 'form'

%h1 All URLs

%table
  %tr
    %th Original URL
    %th Short URL
  - @urls.each do |url|
    %tr
      %td= url.long_url
      %td= link_to url_url(url), url_url(url)
      %td= link_to "Info", [:info, url]

app/views/urls/info.html.haml
%h1= link_to url_url(@url), url_url(@url)
%h2
  Original URL:
  = @url.long_url
%h2 Visits
%table
  %tr
    %th IP Address
    %th Date Visited
  - @url.visits.each do |visit|
    %tr
      %td= visit.ip_address
      -# We can use created_at to get some information about when and how often a user clicks the link
      %td= visit.created_at

app/views/urls/new.html.haml
%h1 Shorten a URL

= render 'form'